DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  fullname TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  datejoined TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  phonenum TEXT,
  isOfficer TEXT NOT NULL DEFAULT False,
  isActive TEXT NOT NULL DEFAULT True,
  isMailed TEXT NOT NULL DEFAULT False
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTENGER NOT NULL,
  username TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
